### PR TITLE
Add `preferredCountries` prop

### PR DESCRIPTION
**Pull request by goveo**
## What has been done
- Added `preferredCountries` feature
  - #139 
- Updated countries ordering logic and preferred section separator redering
- Updated docs

### CODE REVIEW

**Comment by onlywei** [comment]
Whoo hoo!

**Comment by onlywei** [comment]
@goveo how come I don't show up in the [contributors list](https://github.com/goveo/react-international-phone/graphs/contributors) for this?

**Comment by goveo** [comment]
@onlywei Probably your git user email mismatch from that you use on the github, idk how it works actually :(

Even the avatar is not loaded in the preview:
image

**Pull request merged**
